name: crosscheck_sports
description: Fully managed team experience

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.3.9+59
environment:
  sdk: ">=2.17.0 <3.7.3"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  http: ^0.13.3
  provider: ^6.0.5
  google_fonts: ^4.0.3
  sprung: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.0.6
  firebase_core: ^2.7.0 # firebase
  firebase_messaging: ^14.2.5 # firebase
  overlay_support: ^2.1.0 # firebase
  flutter_switch: ^0.3.2
  intl: ^0.17.0 # for date format
  table_calendar: ^3.0.2 # for calendar functionality
  launch_review: ^3.0.1 # for openning the app store page in app
  flutter_datetime_picker: ^1.5.1 # for picking dates for events
  device_info_plus: ^8.1.0 # for getting device id
  flutter_slidable: ^2.0.0 # for slide actions in a list
  flutter_colorpicker: ^1.0.2 # picking color for a team
  flutter_svg: ^2.0.2 # for svg rendering
  graphql: ^5.0.0 # for graphql chat
  uuid: ^3.0.5 # for message id's
  amplify_flutter: ^0.6.12 # for graphql subs
  amplify_api: ^0.6.12 # for graphql subs
  flutter_staggered_grid_view: ^0.6.0 # for better grids
  image_picker: ^0.8.6+4 # for picking images for team logo upload
  image: ^4.0.15 # for resizing images
  flutter_app_badger: ^1.4.0 # for reading and removing notification badges
  firebase_dynamic_links: ^5.0.15 # for in app linking
  firebase_analytics: ^10.1.4
  flutter_image_compress: ^1.1.0 # for compressing images
  cached_network_image: ^3.2.1 # holding network images in cache directory
  flutter_cache_manager: ^3.3.0 # for interacting with network images
  gallery_saver: ^2.3.2 # for saving images to the gallery
  file_picker: ^5.2.5 # better file picker
  video_compress: ^3.1.0 # for compressing videos
  video_thumbnail: ^0.5.2 # for creating video thumbnails
  video_player: ^2.4.6 # for playing video files
  url_launcher: ^6.1.5 # for opening link urls
  device_calendar: ^4.2.0 # for adding events to the user's calendar
  syncfusion_flutter_datepicker: ^20.4.42
  timezone: ^0.9.1
  excel: 2.0.1 # reading excel files for user create
  ical: ^0.2.2
  share_plus: ^6.3.1
  path_provider: ^2.0.14

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launch/x.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rubik/Rubik-Semibold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        # - asset: assets/fonts/rubik/Rubik-Ultralight.ttf
        #   weight: 200
        # - asset: assets/fonts/rubik/Rubik-UltralightItalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: assets/fonts/rubik/Rubik-Thin.ttf
        #   weight: 100
      # - asset: assets/fonts/rubik/Rubik-ThinItlaic.ttf
      #   style: italic
      #   weight: 100
  assets:
    - assets/launch/x.png
    - assets/launch/x_white_centered.png
    - assets/svg/not_found.svg
    - assets/svg/wave1.svg
    - assets/svg/wave2.svg
    - assets/svg/maintenance.svg
    - assets/svg/goalie_mask.svg
    - assets/svg/xcheck_white.svg
    - assets/svg/soccer-goal.svg
    - assets/svg/sapphire.svg
    - assets/svg/login.svg
    - assets/svg/road.svg
    - assets/svg/no_data.svg

    - assets/svg/baseball.svg
    - assets/svg/basketball.svg
    - assets/svg/football.svg
    - assets/svg/hockey.svg
    - assets/svg/soccer.svg
    - assets/svg/golf.svg

    - assets/files/xcheck_roster_input.xlsx

    - assets/images/iphone.png
    - assets/images/android.png





  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
